"""Bundled StoryAura-derived Danbooru character metadata (MIT).

Compact tables generated by ``scripts/build_danbooru_assets.py`` from
https://huggingface.co/datasets/StoryAura/Danbooru-Dataset-csv. Loaded lazily
and cached for the process lifetime.
"""

from __future__ import annotations

import csv
import logging
import threading
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

_LOCK = threading.Lock()
# tag -> (copyright, parent_tag, post_count)
_CHARACTERS: Optional[Dict[str, Tuple[str, str, int]]] = None
_CHARACTER_NAMES: Optional[Set[str]] = None

EXTRA_VOCAB_MIN_POSTS = 50


def _assets_dir() -> Path:
    return Path(__file__).resolve().parent / "assets"


def _characters_csv_path() -> Path:
    return _assets_dir() / "danbooru_characters.csv"


def _character_names_path() -> Path:
    return _assets_dir() / "danbooru_character_names.txt"


def reset_catalog_for_tests() -> None:
    """Testing hook: drop loaded character tables so paths can be re-resolved."""
    global _CHARACTERS, _CHARACTER_NAMES
    with _LOCK:
        _CHARACTERS = None
        _CHARACTER_NAMES = None


def _normalize_tag(raw: str) -> str:
    return str(raw or "").strip().lower().replace(" ", "_")


def _load_characters() -> Dict[str, Tuple[str, str, int]]:
    path = _characters_csv_path()
    rows: Dict[str, Tuple[str, str, int]] = {}
    if not path.is_file():
        return rows
    try:
        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.reader(handle)
            header = next(reader, None)
            if header and _normalize_tag(header[0] if header else "") != "tag":
                handle.seek(0)
                reader = csv.reader(handle)
            for parts in reader:
                if len(parts) < 1:
                    continue
                tag = _normalize_tag(parts[0])
                if not tag or tag.startswith("#"):
                    continue
                copyright_ = parts[1].strip() if len(parts) > 1 else ""
                parent = parts[2].strip() if len(parts) > 2 else ""
                try:
                    count = int(parts[3]) if len(parts) > 3 else 0
                except (TypeError, ValueError):
                    count = 0
                rows[tag] = (copyright_, parent, count)
    except Exception as exc:
        logger.warning("Failed to load character catalog from %s: %s", path, exc)
        return {}
    logger.info("Loaded %d StoryAura character rows from %s", len(rows), path)
    return rows


def _load_character_names() -> Set[str]:
    path = _character_names_path()
    names: Set[str] = set()
    if not path.is_file():
        return names
    try:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                tag = _normalize_tag(line)
                if tag and not tag.startswith("#"):
                    names.add(tag)
    except Exception as exc:
        logger.warning("Failed to load character names from %s: %s", path, exc)
        return set()
    logger.info("Loaded %d StoryAura character names from %s", len(names), path)
    return names


def _ensure_loaded() -> None:
    global _CHARACTERS, _CHARACTER_NAMES
    if _CHARACTERS is not None and _CHARACTER_NAMES is not None:
        return
    with _LOCK:
        if _CHARACTERS is None:
            _CHARACTERS = _load_characters()
        if _CHARACTER_NAMES is None:
            _CHARACTER_NAMES = _load_character_names()


def get_character(tag: str) -> Optional[Dict[str, object]]:
    """Return copyright / parent / post_count for a character tag, if known."""
    _ensure_loaded()
    row = (_CHARACTERS or {}).get(_normalize_tag(tag))
    if row is None:
        return None
    copyright_, parent, count = row
    return {
        "tag": _normalize_tag(tag),
        "copyright": copyright_ or "",
        "parent_tag": parent or "",
        "post_count": int(count),
    }


def get_character_tag_set() -> Set[str]:
    """Popular character names safe to classify without a WD14 download."""
    _ensure_loaded()
    return _CHARACTER_NAMES or set()


def extra_vocab_rows(existing_tags: Set[str]) -> List[Tuple[str, int, int, str]]:
    """Popular characters missing from the main vocabulary, as vocab rows.

    Shape matches ``tag_suggest_service``: (tag, count, category_code, match_blob).
    Category code 4 is danbooru-character.
    """
    _ensure_loaded()
    extra: List[Tuple[str, int, int, str]] = []
    for tag, (_copyright, _parent, count) in (_CHARACTERS or {}).items():
        if count < EXTRA_VOCAB_MIN_POSTS or tag in existing_tags:
            continue
        extra.append((tag, int(count), 4, tag))
    extra.sort(key=lambda row: row[1], reverse=True)
    return extra
