"""
Write-side database operations for images: the derived-state writer core.

Split (2026-07): this module KEEPS the ten defs whose writer statements
tests/test_derived_state_contract.py pins to this exact filename (the
derived-state clear / copy / mark-tagged cursor helpers, the scan upsert
engine, and both metadata rewrite paths) plus the loras / prompt-token
index sync helpers they call. The remaining 17 write entry points moved
verbatim to three sibling modules and are re-imported BY REFERENCE at the
BOTTOM of this file (below the local defs deliberately: each sibling
from-imports shared helpers defined here, so those names must already be
bound on this partially initialized module while the sibling bodies run):

* ``db_images_write_upsert``     — ``add_image`` / ``add_images_batch`` /
  ``get_image_scan_state_by_paths`` / ``_get_existing_images_by_paths``
* ``db_images_write_lifecycle``  — source-path reconnect, path move,
  readable / unreadable transitions, pending-error marking, deletions
* ``db_images_write_attributes`` — caption / user-rating / color writers

``database.py`` re-exports all 27 names from here BY REFERENCE (10 local +
17 re-imported) and ``db_collections`` / ``db_tags`` pull
``_compact_persisted_metadata_json`` / ``_mark_image_tagged`` by name; the
identity contract ``database.X is db_images_write.X`` is locked by
tests/test_db_images_write_pins.py (TestReExportIdentityUnion). The header
import block below stays verbatim from the pre-split module.

Depends on :mod:`db_core`, :mod:`db_helpers`, and ``metadata_storage``; it must
not import from ``database``.
"""
import os
import sqlite3
from datetime import datetime
from typing import Optional, List, Dict, Any, Tuple, Union

from utils.source_paths import (
    build_indexed_image_lookup_candidates,
    indexed_image_path_casefold,
    indexed_image_path_match_key,
)
from caption_format import caption_format_for_storage
from metadata_storage import compact_existing_metadata_json, compact_metadata_json


def _active_library_id_for_write(record: Optional[Dict[str, Any]] = None) -> str:
    """Pin new image rows to the request's long-lived library workspace."""
    if record and record.get("library_id"):
        try:
            from library_context import normalize_library_id

            return normalize_library_id(str(record.get("library_id")))
        except Exception:
            return str(record.get("library_id") or "main")
    try:
        from library_context import get_current_library_id

        return get_current_library_id()
    except Exception:
        return "main"
from db_core import (
    KEEP_EXISTING_SIDECAR_CAPTION,
    get_db,
    _invalidate_facet_caches,
    _invalidate_tags_cache,
)
from db_helpers import (
    _normalize_indexed_image_path,
    _path_query_match_clause,
    normalize_checkpoint_name,
    extract_prompt_tokens,
    extract_lora_names,
    _serialize_loras,
    _normalize_content_fingerprint,
    _row_value,
    _row_to_dict,
    _is_source_fingerprint_changed,
    _should_clear_derived_state,
)


def _clear_image_pixel_caches(cursor: sqlite3.Cursor, image_id: int) -> None:
    """Drop only what has to be recomputed from the image's pixels.

    Safe to call whenever we can no longer trust or reach the pixels, because
    every column here is regenerated by re-running the pipeline that produced it.
    Nothing the user typed or chose is touched.
    """
    cursor.execute(
        """
        UPDATE images
        SET content_fingerprint = NULL,
            embedding = NULL,
            tagged_at = NULL,
            ai_caption = NULL,
            nl_caption = NULL,
            aesthetic_score = NULL,
            ai_rating = NULL,
            ai_rating_confidence = NULL
        WHERE id = ?
        """,
        (image_id,),
    )


def _clear_image_derived_state(cursor: sqlite3.Cursor, image_id: int) -> None:
    """Remove derived data that becomes stale when the source image CHANGED.

    Only for a genuine content change (a new fingerprint at the same path): the
    old tags and predictions describe pixels that no longer exist, so keeping
    them would be worse than losing them.

    Do NOT call this when a file is merely unreachable — see
    ``mark_image_unreadable``. Nothing about the image changed there, and
    deleting tags for an unplugged drive is unrecoverable: a later reconnect
    restores the row but cannot restore the tags.
    """
    _clear_image_pixel_caches(cursor, image_id)
    cursor.execute("DELETE FROM tags WHERE image_id = ?", (image_id,))
    cursor.execute("DELETE FROM tag_scores WHERE image_id = ?", (image_id,))
    cursor.execute("DELETE FROM tag_writer_provenance WHERE image_id = ?", (image_id,))
    cursor.execute("DELETE FROM artist_predictions WHERE image_id = ?", (image_id,))

def _sync_image_loras(
    cursor: sqlite3.Cursor,
    image_id: int,
    loras: Optional[List[str]],
    prompt: Optional[str],
) -> None:
    """Refresh the normalized image_loras rows for an image."""
    cursor.execute("DELETE FROM image_loras WHERE image_id = ?", (image_id,))

    lora_names = extract_lora_names(_serialize_loras(loras) or '', prompt or '')
    for lora_name in lora_names:
        cursor.execute(
            "INSERT OR IGNORE INTO image_loras (image_id, lora_name) VALUES (?, ?)",
            (image_id, lora_name)
        )

def _sync_image_prompt_tokens(
    cursor: sqlite3.Cursor,
    image_id: int,
    prompt: Optional[str],
) -> None:
    """Refresh the normalized image_prompt_tokens rows for an image."""
    cursor.execute("DELETE FROM image_prompt_tokens WHERE image_id = ?", (image_id,))

    for token in extract_prompt_tokens(prompt or ''):
        cursor.execute(
            "INSERT OR IGNORE INTO image_prompt_tokens (image_id, token) VALUES (?, ?)",
            (image_id, token),
        )

def _compact_persisted_metadata_json(metadata_json: Any) -> str:
    compacted = compact_existing_metadata_json(metadata_json)
    if compacted is not None:
        return compacted
    return compact_metadata_json({})


def _sync_image_path_identity(
    cursor: sqlite3.Cursor,
    image_id: int,
    path: str,
) -> None:
    """Refresh the materialized canonical path identity for an image."""
    path_key = indexed_image_path_casefold(_normalize_indexed_image_path(path))
    if not path_key:
        cursor.execute(
            "DELETE FROM image_path_identities WHERE image_id = ?",
            (image_id,),
        )
        return
    cursor.execute(
        "INSERT INTO image_path_identities (image_id, path_key) VALUES (?, ?) "
        "ON CONFLICT(image_id) DO UPDATE SET path_key = excluded.path_key",
        (image_id, path_key),
    )


def _upsert_image_record(
    cursor: sqlite3.Cursor,
    record: Dict[str, Any],
    existing_row: Optional[sqlite3.Row] = None,
) -> Tuple[int, str]:
    """Insert or update a single image row using an existing transaction."""
    path = _normalize_indexed_image_path(record["path"])
    record["metadata_json"] = _compact_persisted_metadata_json(record.get("metadata_json"))
    serialized_loras = _serialize_loras(record.get("loras"))
    metadata_status = record.get("metadata_status") or "complete"
    record["checkpoint_normalized"] = normalize_checkpoint_name(record.get("checkpoint"))
    incoming_library_order_time = record.get("library_order_time")
    if incoming_library_order_time is None:
        incoming_library_order_time = record.get("created_at")
    incoming_source_file_mtime = record.get("source_file_mtime")
    if incoming_source_file_mtime is None:
        incoming_source_file_mtime = record.get("created_at")
    record["library_order_time"] = incoming_library_order_time
    record["source_file_mtime"] = incoming_source_file_mtime
    record["created_at"] = incoming_library_order_time
    source_changed = False
    mark_unreadable = not record.get("is_readable", True)

    if existing_row is None:
        candidates = build_indexed_image_lookup_candidates(path)
        if candidates:
            query_clause, query_params = _path_query_match_clause(candidates)
            existing_rows = cursor.execute(
                f"""
                SELECT id, path, source_mtime_ns, source_size, content_fingerprint,
                       library_order_time, source_file_mtime, created_at,
                       tagged_at, ai_caption, aesthetic_score,
                       COALESCE(library_id, 'main') AS library_id,
                       CASE WHEN embedding IS NOT NULL THEN 1 ELSE 0 END AS has_embedding,
                       EXISTS(SELECT 1 FROM artist_predictions ap WHERE ap.image_id = images.id) AS has_artist_predictions
                FROM images
                WHERE {query_clause}
                """,
                query_params,
            ).fetchall()
            rows_by_path = {row["path"]: row for row in existing_rows}
            rows_by_match_key = {
                indexed_image_path_match_key(row["path"]): row
                for row in existing_rows
            }
            for candidate in candidates:
                existing_row = rows_by_path.get(candidate)
                if not existing_row:
                    existing_row = rows_by_match_key.get(indexed_image_path_match_key(candidate))
                if existing_row:
                    break

    if existing_row:
        image_id = existing_row["id"]
        # Path is globally unique: do not steal a row owned by another library.
        try:
            existing_lib = existing_row["library_id"]
        except (KeyError, IndexError, TypeError):
            existing_lib = None
        if existing_lib is None:
            try:
                lib_row = cursor.execute(
                    "SELECT COALESCE(library_id, 'main') AS library_id FROM images WHERE id = ?",
                    (image_id,),
                ).fetchone()
                existing_lib = lib_row["library_id"] if lib_row else "main"
            except Exception:
                existing_lib = "main"
        target_lib = _active_library_id_for_write(record)
        try:
            from library_context import normalize_library_id

            existing_lib_norm = normalize_library_id(str(existing_lib or "main"))
            target_lib_norm = normalize_library_id(str(target_lib or "main"))
        except Exception:
            existing_lib_norm = str(existing_lib or "main")
            target_lib_norm = str(target_lib or "main")
        if existing_lib_norm != target_lib_norm:
            return image_id, "skipped_other_library"

        write_status = "updated"
        source_changed = _is_source_fingerprint_changed(existing_row, record)
        incoming_source_mtime_ns = record.get("source_mtime_ns")
        incoming_source_size = record.get("source_size")
        if metadata_status == "pending":
            # Placeholder scan rows should not consume the new source fingerprint
            # before the final metadata backfill has a chance to compare pixels.
            incoming_source_mtime_ns = None
            incoming_source_size = None
        if _should_clear_derived_state(
            existing_row,
            record,
            source_changed=source_changed,
            mark_unreadable=mark_unreadable,
        ):
            _clear_image_derived_state(cursor, image_id)

        # sidecar_fingerprint is COALESCEd rather than assigned: a NULL in the
        # record means the caller could not question the filesystem about
        # sidecars, which must not be mistaken for "this image has no sidecar"
        # (recorded as an empty string by sidecar_fingerprint.py).
        #
        # sidecar_caption_format is DERIVED here from the caption text this
        # statement is about to store, not taken from the record. Deriving it at
        # the write boundary is what makes the marker and the text structurally
        # unable to disagree, whatever a caller passes. It never affects the
        # caption value itself.
        cursor.execute(
            """
            UPDATE images
            SET filename = ?,
                generator = ?,
                prompt = ?,
                sidecar_caption = ?,
                sidecar_caption_format = ?,
                negative_prompt = ?,
                metadata_json = ?,
                width = ?,
                height = ?,
                file_size = ?,
                checkpoint = ?,
                checkpoint_normalized = ?,
                loras = ?,
                model_hash = COALESCE(?, model_hash),
                is_readable = ?,
                read_error = ?,
                source_mtime_ns = COALESCE(?, source_mtime_ns),
                source_size = COALESCE(?, source_size),
                metadata_status = ?,
                content_fingerprint = COALESCE(?, content_fingerprint),
                sidecar_fingerprint = COALESCE(?, sidecar_fingerprint),
                library_order_time = COALESCE(library_order_time, created_at, ?),
                source_file_mtime = COALESCE(?, source_file_mtime),
                created_at = COALESCE(library_order_time, created_at, ?),
                raw_metadata_gz = CASE
                    WHEN ? IS NOT NULL THEN ?
                    WHEN ? IS NOT NULL AND TRIM(?) != '' THEN NULL
                    ELSE raw_metadata_gz
                END,
                indexed_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                record["filename"],
                record.get("generator", "unknown"),
                record.get("prompt"),
                record.get("sidecar_caption"),
                caption_format_for_storage(record.get("sidecar_caption")),
                record.get("negative_prompt"),
                record.get("metadata_json"),
                record.get("width"),
                record.get("height"),
                record.get("file_size"),
                record.get("checkpoint"),
                record.get("checkpoint_normalized"),
                serialized_loras,
                record.get("model_hash"),
                1 if record.get("is_readable", True) else 0,
                record.get("read_error"),
                incoming_source_mtime_ns,
                incoming_source_size,
                metadata_status,
                record.get("content_fingerprint"),
                record.get("sidecar_fingerprint"),
                record.get("library_order_time"),
                record.get("source_file_mtime"),
                record.get("created_at"),
                # raw_metadata_gz invariant: rows only keep a raw envelope
                # while their prompt is missing. New raw wins; a successful
                # parse clears any stale raw; otherwise the stored raw
                # survives placeholder/rescan updates.
                record.get("raw_metadata_gz"),
                record.get("raw_metadata_gz"),
                record.get("prompt"),
                record.get("prompt"),
                image_id,
            ),
        )
    else:
        write_status = "new"
        cursor.execute(
            """
            INSERT INTO images
            (path, filename, generator, prompt, sidecar_caption, sidecar_caption_format,
             negative_prompt, metadata_json,
             width, height, file_size, checkpoint, checkpoint_normalized, loras, model_hash, is_readable, read_error,
             source_mtime_ns, source_size, metadata_status, content_fingerprint, sidecar_fingerprint,
             library_order_time, source_file_mtime, created_at, raw_metadata_gz, indexed_at, library_id)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, ?)
            """,
            (
                path,
                record["filename"],
                record.get("generator", "unknown"),
                record.get("prompt"),
                record.get("sidecar_caption"),
                caption_format_for_storage(record.get("sidecar_caption")),
                record.get("negative_prompt"),
                record.get("metadata_json"),
                record.get("width"),
                record.get("height"),
                record.get("file_size"),
                record.get("checkpoint"),
                record.get("checkpoint_normalized"),
                serialized_loras,
                record.get("model_hash"),
                1 if record.get("is_readable", True) else 0,
                record.get("read_error"),
                record.get("source_mtime_ns"),
                record.get("source_size"),
                metadata_status,
                record.get("content_fingerprint"),
                record.get("sidecar_fingerprint"),
                record.get("library_order_time"),
                record.get("source_file_mtime"),
                record.get("created_at"),
                record.get("raw_metadata_gz"),
                _active_library_id_for_write(record),
            ),
        )
        image_id = cursor.lastrowid

    stored_path = str(existing_row["path"]) if existing_row is not None else path
    _sync_image_path_identity(cursor, image_id, stored_path)
    _sync_image_loras(cursor, image_id, record.get("loras"), record.get("prompt"))
    _sync_image_prompt_tokens(cursor, image_id, record.get("prompt"))
    return image_id, write_status

def _mark_image_tagged(
    cursor: sqlite3.Cursor,
    image_id: int,
    content_fingerprint: Optional[str],
) -> None:
    cursor.execute(
        "UPDATE images SET tagged_at = CURRENT_TIMESTAMP, content_fingerprint = COALESCE(?, content_fingerprint) WHERE id = ?",
        (content_fingerprint, image_id),
    )

def _copy_image_derived_state(cursor: sqlite3.Cursor, source_image_id: int, target_image_id: int) -> None:
    """Copy cached derived fields that remain valid for file duplicates using an existing transaction."""
    if source_image_id == target_image_id:
        return

    source_row = cursor.execute(
        """
        SELECT tagged_at, ai_caption, nl_caption, aesthetic_score, embedding, content_fingerprint
        FROM images
        WHERE id = ?
        """,
        (source_image_id,),
    ).fetchone()
    if source_row:
        cursor.execute(
            """
            UPDATE images
            SET tagged_at = ?,
                ai_caption = ?,
                nl_caption = ?,
                aesthetic_score = ?,
                embedding = ?,
                content_fingerprint = COALESCE(?, content_fingerprint)
            WHERE id = ?
            """,
            (
                source_row["tagged_at"],
                source_row["ai_caption"],
                source_row["nl_caption"],
                source_row["aesthetic_score"],
                source_row["embedding"],
                source_row["content_fingerprint"],
                target_image_id,
            ),
        )

    artist_row = cursor.execute(
        """
        SELECT artist, confidence, top_predictions, identified_at
        FROM artist_predictions
        WHERE image_id = ?
        """,
        (source_image_id,),
    ).fetchone()
    if artist_row:
        cursor.execute(
            """
            INSERT INTO artist_predictions (
                image_id, artist, confidence, top_predictions, identified_at
            )
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(image_id) DO UPDATE SET
                artist = excluded.artist,
                confidence = excluded.confidence,
                top_predictions = excluded.top_predictions,
                identified_at = excluded.identified_at
            """,
            (
                target_image_id,
                artist_row["artist"],
                artist_row["confidence"],
                artist_row["top_predictions"],
                artist_row["identified_at"],
            ),
        )

def copy_image_derived_state(source_image_id: int, target_image_id: int) -> None:
    """Copy cached derived fields that remain valid for file duplicates."""
    with get_db() as conn:
        _copy_image_derived_state(conn.cursor(), source_image_id, target_image_id)

def update_image_metadata(
    image_id: int,
    generator: str,
    prompt: Optional[str],
    negative_prompt: Optional[str],
    metadata_json: Optional[str],
    width: Optional[int],
    height: Optional[int],
    file_size: Optional[int],
    checkpoint: Optional[str],
    loras: Optional[List[str]],
    model_hash: Optional[str] = None,
    is_readable: Optional[bool] = None,
    read_error: Optional[str] = None,
    source_mtime_ns: Optional[int] = None,
    source_size: Optional[int] = None,
    metadata_status: Optional[str] = None,
    content_fingerprint: Optional[str] = None,
    preserve_derived_state: bool = False,
    sidecar_caption: Any = KEEP_EXISTING_SIDECAR_CAPTION,
):
    """Update parsed metadata fields for an existing image without replacing the row."""
    metadata_json = _compact_persisted_metadata_json(metadata_json)
    rewrite_sidecar_caption = sidecar_caption is not KEEP_EXISTING_SIDECAR_CAPTION
    with get_db() as conn:
        cursor = conn.cursor()
        serialized_loras = _serialize_loras(loras)
        checkpoint_normalized = normalize_checkpoint_name(checkpoint)
        metadata_status_normalized = str(metadata_status or "").strip().lower()
        existing_row = cursor.execute(
            """
            SELECT id, source_mtime_ns, source_size, content_fingerprint,
                   tagged_at, ai_caption, aesthetic_score,
                   CASE WHEN embedding IS NOT NULL THEN 1 ELSE 0 END AS has_embedding,
                   EXISTS(SELECT 1 FROM artist_predictions ap WHERE ap.image_id = images.id) AS has_artist_predictions
            FROM images
            WHERE id = ?
            """,
            (image_id,),
        ).fetchone()
        source_changed = _is_source_fingerprint_changed(
            existing_row,
            {
                "source_mtime_ns": source_mtime_ns,
                "source_size": source_size,
            },
        )
        mark_unreadable = (is_readable is False)
        existing_fingerprint = _normalize_content_fingerprint(_row_value(existing_row, "content_fingerprint"))
        incoming_fingerprint = _normalize_content_fingerprint(content_fingerprint)
        can_preserve_derived_state = bool(
            preserve_derived_state
            and not mark_unreadable
            and metadata_status_normalized == "complete"
            and existing_fingerprint is not None
            and incoming_fingerprint is not None
            and existing_fingerprint == incoming_fingerprint
        )
        if (
            _should_clear_derived_state(
                existing_row,
                {
                    "source_mtime_ns": source_mtime_ns,
                    "source_size": source_size,
                    "metadata_status": metadata_status,
                    "content_fingerprint": content_fingerprint,
                },
                source_changed=source_changed,
                mark_unreadable=mark_unreadable,
            )
            and not can_preserve_derived_state
        ):
            _clear_image_derived_state(cursor, image_id)
        cursor.execute(
            """
            UPDATE images
            SET generator = ?,
                prompt = ?,
                sidecar_caption = CASE WHEN ? = 1 THEN ? ELSE sidecar_caption END,
                sidecar_caption_format =
                    CASE WHEN ? = 1 THEN ? ELSE sidecar_caption_format END,
                negative_prompt = ?,
                metadata_json = ?,
                width = ?,
                height = ?,
                file_size = ?,
                checkpoint = ?,
                checkpoint_normalized = ?,
                loras = ?,
                model_hash = COALESCE(?, model_hash),
                is_readable = COALESCE(?, is_readable),
                read_error = ?,
                source_mtime_ns = COALESCE(?, source_mtime_ns),
                source_size = COALESCE(?, source_size),
                metadata_status = COALESCE(?, metadata_status),
                content_fingerprint = COALESCE(?, content_fingerprint),
                raw_metadata_gz = CASE
                    WHEN ? IS NOT NULL AND TRIM(?) != '' THEN NULL
                    ELSE raw_metadata_gz
                END,
                indexed_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                generator,
                prompt,
                1 if rewrite_sidecar_caption else 0,
                sidecar_caption if rewrite_sidecar_caption else None,
                # Same CASE guard, same derivation source: a caller that knows
                # nothing about captions rewrites neither the text nor its marker.
                1 if rewrite_sidecar_caption else 0,
                (
                    caption_format_for_storage(sidecar_caption)
                    if rewrite_sidecar_caption
                    else None
                ),
                negative_prompt,
                metadata_json,
                width,
                height,
                file_size,
                checkpoint,
                checkpoint_normalized,
                serialized_loras,
                model_hash,
                None if is_readable is None else (1 if is_readable else 0),
                read_error,
                source_mtime_ns,
                source_size,
                metadata_status,
                content_fingerprint,
                # L3 invariant: a successful re-parse clears the stored raw
                # envelope; a failed one keeps it for future parser upgrades.
                prompt,
                prompt,
                image_id,
            )
        )
        _sync_image_loras(cursor, image_id, loras, prompt)
        _sync_image_prompt_tokens(cursor, image_id, prompt)
    _invalidate_tags_cache()

def update_reparsed_prompt_fields(
    image_id: int,
    *,
    prompt: str,
    negative_prompt: Optional[str] = None,
    checkpoint: Optional[str] = None,
    loras: Optional[List[str]] = None,
    generator: Optional[str] = None,
    sidecar_caption: Optional[str] = None,
) -> None:
    """Targeted write for the metadata re-parse job (L3).

    Unlike ``update_image_metadata`` this touches ONLY prompt-derived
    fields, so a replay from the stored raw envelope can never wipe
    width/height/source bookkeeping it knows nothing about. Checkpoint,
    loras, negative prompt, generator and the sidecar caption only fill in
    when the replay produced them (scan-time values may already be correct).
    Clears ``raw_metadata_gz`` — a recovered row no longer needs repair.
    """
    with get_db() as conn:
        cursor = conn.cursor()
        serialized_loras = _serialize_loras(loras) if loras else None
        cursor.execute(
            """
            UPDATE images
            SET prompt = ?,
                negative_prompt = COALESCE(?, negative_prompt),
                generator = COALESCE(?, generator),
                checkpoint = COALESCE(?, checkpoint),
                checkpoint_normalized = COALESCE(?, checkpoint_normalized),
                loras = COALESCE(?, loras),
                sidecar_caption = COALESCE(?, sidecar_caption),
                sidecar_caption_format = COALESCE(?, sidecar_caption_format),
                raw_metadata_gz = NULL,
                indexed_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (
                prompt,
                negative_prompt,
                generator,
                checkpoint,
                normalize_checkpoint_name(checkpoint) if checkpoint else None,
                serialized_loras,
                sidecar_caption,
                # Same COALESCE shape as the caption above: no caption in this
                # replay means the stored caption AND its marker both survive.
                caption_format_for_storage(sidecar_caption),
                image_id,
            ),
        )
        # The lora/token indexes must mirror the post-COALESCE row, so
        # read the merged values back instead of trusting the arguments.
        final_row = cursor.execute(
            "SELECT prompt, loras FROM images WHERE id = ?",
            (image_id,),
        ).fetchone()
        final_prompt = final_row["prompt"] if final_row else prompt
        final_loras_serialized = (final_row["loras"] if final_row else None) or ""
        cursor.execute("DELETE FROM image_loras WHERE image_id = ?", (image_id,))
        for lora_name in extract_lora_names(final_loras_serialized, final_prompt or ""):
            cursor.execute(
                "INSERT OR IGNORE INTO image_loras (image_id, lora_name) VALUES (?, ?)",
                (image_id, lora_name),
            )
        _sync_image_prompt_tokens(cursor, image_id, final_prompt)
    _invalidate_tags_cache()
    _invalidate_facet_caches()

def update_reparsed_sidecar_caption(image_id: int, sidecar_caption: str) -> None:
    """Store caption text the re-parse job recovered from a sidecar.

    Deliberately narrower than :func:`update_reparsed_prompt_fields`: the row
    still has no SD generation prompt, so ``prompt`` stays empty, the prompt
    token index is untouched, and ``raw_metadata_gz`` is KEPT so a future
    parser upgrade can still try to find a real prompt in the same bytes.
    """
    with get_db() as conn:
        conn.execute(
            """
            UPDATE images
            SET sidecar_caption = ?,
                sidecar_caption_format = ?,
                indexed_at = CURRENT_TIMESTAMP
            WHERE id = ?
            """,
            (sidecar_caption, caption_format_for_storage(sidecar_caption), image_id),
        )

# --- Split re-exports (2026-07) --------------------------------------------
# Deliberately at the BOTTOM: the sibling modules from-import the shared
# cursor helpers defined above, so this module must bind them before the
# sibling bodies run (managed import cycle). Consumers never import the
# siblings directly -- they import ``database`` (or this module), so this
# module always loads first.
from db_images_write_upsert import (
    add_image,
    _get_existing_images_by_paths,
    add_images_batch,
    get_image_scan_state_by_paths,
)
from db_images_write_lifecycle import (
    reconnect_image_source_path,
    delete_images_by_ids,
    delete_images_by_paths,
    mark_pending_images_metadata_error,
    update_image_path,
    mark_image_unreadable,
    mark_image_unreadable_by_path,
    mark_image_readable,
    delete_image,
)
from db_images_write_attributes import (
    update_image_caption,
    set_image_captions,
    set_user_rating,
    update_image_colors,
)
